services:
  - type: web
    name: django-app
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput"
    startCommand: "gunicorn DjangoProjectFinal.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.8
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoProjectFinal.settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: 'False'
      # Agrega aquí tus variables de entorno necesarias
      # - key: SECRET_KEY
      #   generateValue: true
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: your-db-name
      #     property: connectionString
