# Generated by Django 5.2.3 on 2025-06-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemcarrito',
            options={'verbose_name': 'Ítem de carrito', 'verbose_name_plural': 'Ítems de carrito'},
        ),
    ]
